services:
  - type: web
    name: shahen2
    runtime: python
    buildCommand: cd backend && bash build.sh
    startCommand: cd backend && bash start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: shahen2.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://shahen2.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://shahen2.onrender.com
      - key: CORS_ORIGIN_ALLOW_ALL
        value: "False"
      - key: API_AUTH_REQUIRED
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "True"
      - key: SECRET_KEY
        generateValue: true
